services:
  - type: web
    name: gemnibot-backend
    runtime: docker
    plan: free
    rootDir: gemnibot
    buildCommand: docker build -t gemnibot-backend .
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_URL
        value: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=

  - type: web
    name: gemnibot
    runtime: static
    rootDir: gemnibot-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://gemnibot-backend.onrender.com/api/qna/ask